---
- name: Install Vector
  # hosts: clickhouse
  hosts: click-srv
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
        enabled: yes
  tasks:

  - name: install nano
    become: true
    ansible.builtin.yum:
      name:
        - nano
  
  - name: Add user vector
    user:
      name: vector
#      shell: /bin/bash
#      home: /home/baeldung


  - name: Create Directories
    file:
      path: "{{ item }}"
      state: directory
      owner: vector
      group: vector
      mode: 0755
    loop:
      - '/vector/'
      - '/var/lib/vector'
      - '/etc/vector'




    # - block:
  - name: Get vector distrib
    ansible.builtin.get_url:
      # url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
      dest: "/vector/vector-{{ clickhouse_version }}.tar.gz"

  - name: Unpack vector
    unarchive:
      src: "/vector/vector-{{ clickhouse_version }}.tar.gz"
      dest: "/vector/"
      remote_src: yes

  - name: Копирование файла запускного вектора
    copy:
      src: "/vector/vector-x86_64-unknown-linux-musl/bin/vector"
      dest: "/usr/bin/vector"
      owner: vector
      group: vector
      #mode: 0755
      remote_src: yes

  - name: Копирование файла сервиса вектора
    copy:
      src: "/vector/vector-x86_64-unknown-linux-musl/etc/systemd/vector.service"
      dest: "/etc/systemd/system"
      #mode: 0644
      remote_src: yes

  # - name: Копирование файла конфига вектора
  #   copy:
  #     src: "/vector/vector-x86_64-unknown-linux-musl/config/vector.yaml"
  #     dest: "/etc/vector/vector.yaml"
  #     #mode: 0755
  #     remote_src: yes

  - name: Создание конфига через шаблон
    template:
      src: "templates/vector.yaml.j2"
      dest: "/etc/vector/vector.yaml"
    notify: Start vector service


  # # handlers:
  # - name: Start vector service
  #   become: true
  #   # become_method: su
  #   # become_user: root
  #   ansible.builtin.service:
  #     name: vector
  #     state: restarted
  #     enabled: yes

# /vector/vector-x86_64-unknown-linux-musl/etc/systemd/vector.service


    # - name: Install clickhouse packages
    #   become: true
    #   ansible.builtin.yum:
    #     name:
    #       - clickhouse-common-static-{{ clickhouse_version }}.rpm
    #       - clickhouse-client-{{ clickhouse_version }}.rpm
    #       - clickhouse-server-{{ clickhouse_version }}.rpm
    #   notify: Start clickhouse service
    # - name: Flush handlers
    #   meta: flush_handlers
    # - name: Create database
    #   ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
    #   register: create_db
    #   failed_when: create_db.rc != 0 and create_db.rc !=82
    #   changed_when: create_db.rc == 0